name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  APP_DB_USERNAME: postgres
  APP_DB_PASSWORD: ${{ secrets.DB_password }}
  APP_DB_NAME: postgres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - run: go mod tidy

      - name: Start services
        run: docker compose up -d

      - name: Run tests
        run: go test -v ./...

      - run: go build -v ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          sonar.projectKey: ${{ secrets.SONAR_PROJECT_KEY }}  # Your SonarCloud Project Key
          sonar.organization: ${{ secrets.SONAR_ORG }}  # Your SonarCloud Organization Key
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
